// Project: crop2cloud24

// Dataset: LINEAR_CORN_trt1
Table LINEAR_CORN_trt1.plot_5006 {
  TIMESTAMP varchar
  IRT5006B1xx24 float
  TDR5006B10624 float
  TDR5006B11824 float
  TDR5006B13024 float
  TDR5006B14224 float
  DEN5006B1xx24 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  swsi float
  eto float
  etc float
  kc float
  recommendation float
}

Table LINEAR_CORN_trt1.plot_5010 {
  TIMESTAMP varchar
  IRT5010C1xx24 float
  TDR5010C10624 float
  TDR5010C11824 float
  TDR5010C13024 float
  DEN5010C1xx24 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  swsi float
  eto float
  etc float
  kc float
  recommendation float
}

Table LINEAR_CORN_trt1.plot_5023 {
  TIMESTAMP varchar
  IRT5023A1xx24 float
  TDR5023A10624 float
  TDR5023A11824 float
  TDR5023A13024 float
  TDR5023A14224 float
  DEN5023A1xx24 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  swsi float
  eto float
  etc float
  kc float
  recommendation float
}

// Dataset: LINEAR_CORN_trt2
Table LINEAR_CORN_trt2.plot_5003 {
  TIMESTAMP varchar
  IRT5003C2xx24 float
  TDR5003C20624 float
  TDR5003C21824 float
  TDR5003C23024 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  swsi float
  eto float
  etc float
  kc float
  recommendation varchar
}

Table LINEAR_CORN_trt2.plot_5012 {
  TIMESTAMP varchar
  IRT5012B2xx24 float
  TDR5012B20624 float
  TDR5012B21824 float
  TDR5012B23024 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  swsi float
  eto float
  etc float
  kc float
  recommendation varchar
}

Table LINEAR_CORN_trt2.plot_5026 {
  TIMESTAMP varchar
  TDR5026A20624 float
  TDR5026A21824 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  swsi float
  eto float
  etc float
  kc float
}

// Dataset: LINEAR_CORN_trt3
Table LINEAR_CORN_trt3.plot_5001 {
  TIMESTAMP varchar
  IRT5001C3xx24 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  eto float
  etc float
  kc float
  recommendation varchar
}

Table LINEAR_CORN_trt3.plot_5018 {
  TIMESTAMP varchar
  IRT5018A3xx24 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  eto float
  etc float
  kc float
  recommendation varchar
}

Table LINEAR_CORN_trt3.plot_5020 {
  TIMESTAMP varchar
  IRT5020A3xx24 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  eto float
  etc float
  kc float
  recommendation varchar
}

// Dataset: LINEAR_CORN_trt4
Table LINEAR_CORN_trt4.plot_5007 {
  TIMESTAMP varchar
  TDR5007B40624 float
  TDR5007B41824 float
  TDR5007B43024 float
  TDR5007B44224 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  eto float
  etc float
  kc float
}

Table LINEAR_CORN_trt4.plot_5009 {
  TIMESTAMP varchar
  TDR5009C40624 float
  TDR5009C41824 float
  TDR5009C43024 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  eto float
  etc float
  kc float
}

Table LINEAR_CORN_trt4.plot_5027 {
  TIMESTAMP varchar
  TDR5027A40624 float
  TDR5027A41824 float
  TDR5027A43024 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  eto float
  etc float
  kc float
}

// Dataset: LINEAR_SOYBEAN_trt1
Table LINEAR_SOYBEAN_trt1.plot_2006 {
  TIMESTAMP varchar
  IRT2006B1xx24 float
  TDR2006B10624 float
  TDR2006B11824 float
  TDR2006B13024 float
  TDR2006B14224 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  swsi float
  eto float
  etc float
  kc float
  recommendation float
}

Table LINEAR_SOYBEAN_trt1.plot_2015 {
  TIMESTAMP varchar
  IRT2015C1xx24 float
  TDR2015C10624 float
  TDR2015C11824 float
  TDR2015C13024 float
  TDR2015C14224 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  swsi float
  eto float
  etc float
  kc float
  recommendation float
}

Table LINEAR_SOYBEAN_trt1.plot_2023 {
  TIMESTAMP varchar
  IRT2023C1xx24 float
  TDR2023C10624 float
  TDR2023C11824 float
  TDR2023C13024 float
  TDR2023C14224 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  swsi float
  eto float
  etc float
  kc float
  recommendation float
}

// Dataset: LINEAR_SOYBEAN_trt2
Table LINEAR_SOYBEAN_trt2.plot_2001 {
  TIMESTAMP varchar
  IRT2001A2xx24 float
  TDR2001A20624 float
  TDR2001A21824 float
  TDR2001A23024 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  swsi float
  eto float
  etc float
  kc float
  recommendation varchar
}

Table LINEAR_SOYBEAN_trt2.plot_2011 {
  TIMESTAMP varchar
  IRT2011B2xx24 float
  TDR2011B20624 float
  TDR2011B21824 float
  TDR2011B23024 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  swsi float
  eto float
  etc float
  kc float
  recommendation varchar
}

Table LINEAR_SOYBEAN_trt2.plot_2026 {
  TIMESTAMP varchar
  TDR2026C23024 float
  TDR2026C21824 float
  TDR2026C20624 float
  IRT2026C2xx24 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  swsi float
  eto float
  etc float
  kc float
  recommendation varchar
}

// Dataset: LINEAR_SOYBEAN_trt3
Table LINEAR_SOYBEAN_trt3.plot_2003 {
  TIMESTAMP varchar
  IRT2003A3xx24 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  eto float
  etc float
  kc float
  recommendation varchar
}

Table LINEAR_SOYBEAN_trt3.plot_2018 {
  TIMESTAMP varchar
  IRT2018C3xx24 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  eto float
  etc float
  kc float
  recommendation varchar
}

Table LINEAR_SOYBEAN_trt3.plot_2020 {
  TIMESTAMP varchar
  IRT2020C3xx24 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  cwsi float
  eto float
  etc float
  kc float
  recommendation varchar
}

// Dataset: LINEAR_SOYBEAN_trt4
Table LINEAR_SOYBEAN_trt4.plot_2009 {
  TIMESTAMP varchar
  TDR2009A40624 float
  TDR2009A41824 float
  TDR2009A43024 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  eto float
  etc float
  kc float
}

Table LINEAR_SOYBEAN_trt4.plot_2012 {
  TIMESTAMP varchar
  TDR2012B40624 float
  TDR2012B41824 float
  TDR2012B43024 float
  Ta_2m_Avg float
  RH_2m_Avg float
  WndAveSpd_3m float
  WndAveDir_3m float
  PresAvg_1pnt5m float
  Solar_2m_Avg float
  Rain_1m_Tot float
  TaMax_2m float
  TaMin_2m float
  RHMax_2m float
  RHMin_2m float
  eto float
  etc float
  kc float
}

